#include <SDL_mixer.h>


// General

int Mix_OpenAudio(int frequency, uint16_t format, int channels, int chunksize) {
  return 0;
}

/**
 * Closes the audio device and frees any resources associated with it.
 * This function should be called when audio playback is no longer needed
 * to ensure proper cleanup of the audio system. After calling this function,
 * the audio device will no longer be available for use, and any subsequent
 * calls to audio-related functions may result in undefined behavior unless
 * the audio system is reinitialized.
 */
void Mix_CloseAudio() {
}

/**
 * @brief Retrieves the last error message generated by the Mix library.
 *
 * This function returns a pointer to a string containing the last error message
 * that occurred in the Mix library. If no error has occurred, the function returns
 * an empty string. The returned string is statically allocated and should not be
 * freed by the caller.
 *
 * @return A pointer to a null-terminated string containing the last error message,
 *         or an empty string if no error has occurred.
 */
char *Mix_GetError() {
    return "";
}

/**
 * Queries the audio specification of the current audio device or context.
 * This function retrieves the sample frequency, audio format, and number of channels
 * of the audio being processed or played back. The values are returned through the
 * provided pointers.
 *
 * @param frequency Pointer to an integer where the sample frequency (in Hz) will be stored.
 * @param format Pointer to a uint16_t where the audio format will be stored. The format is
 *               typically represented as a SDL_AudioFormat value.
 * @param channels Pointer to an integer where the number of audio channels will be stored.
 * @return Returns 0 on success or a negative error code on failure.
 */
int Mix_QuerySpec(int *frequency, uint16_t *format, int *channels) {
  return 0;
}

// Samples

Mix_Chunk *Mix_LoadWAV_RW(SDL_RWops *src, int freesrc) {
  return NULL;
}

/**
 * @brief Frees the memory allocated for a Mix_Chunk object.
 *
 * This function deallocates the memory associated with the given Mix_Chunk object.
 * It should be called when the chunk is no longer needed to avoid memory leaks.
 * After calling this function, the pointer to the Mix_Chunk object should not be used
 * as it will be invalid.
 *
 * @param chunk Pointer to the Mix_Chunk object to be freed. If NULL, the function does nothing.
 */
void Mix_FreeChunk(Mix_Chunk *chunk) {
}


// Channels

int Mix_AllocateChannels(int numchans) {
  return 0;
}

/**
 * Sets the volume for a specified audio channel and returns the new volume.
 * 
 * This function adjusts the volume of the audio channel identified by `channel`
 * to the specified `volume` level. The volume is typically represented as an
 * integer value, where 0 corresponds to silence, and the maximum value (e.g., 128)
 * corresponds to the highest volume level. If the `channel` is invalid or the
 * operation fails, the function may return 0.
 * 
 * @param channel The identifier of the audio channel whose volume is to be set.
 * @param volume The desired volume level to set for the specified channel.
 * @return The new volume level of the channel, or 0 if the operation fails.
 */
int Mix_Volume(int channel, int volume) {
  return 0;
}

/**
 * Plays a given audio chunk on a specified channel with a specified number of loops.
 *
 * This function plays the provided `Mix_Chunk` audio data on the specified `channel`.
 * The audio will loop for the number of times specified by `loops`. If `loops` is set to -1,
 * the audio will loop indefinitely until explicitly stopped. If `channel` is set to -1, the
 * first available channel will be used.
 *
 * @param channel The channel on which to play the audio chunk. Use -1 to play on the first available channel.
 * @param chunk Pointer to the `Mix_Chunk` containing the audio data to be played.
 * @param loops The number of times to loop the audio. Use -1 for infinite looping.
 *
 * @return 0 on success, or -1 if an error occurred (e.g., invalid channel or chunk).
 */
int Mix_PlayChannel(int channel, Mix_Chunk *chunk, int loops) {
  return 0;
}

/**
 * Pauses playback on the specified audio channel.
 *
 * This function temporarily stops the playback of the audio on the given channel.
 * The audio can be resumed later using the `Mix_Resume` function. If the channel
 * is already paused, this function has no effect.
 *
 * @param channel The channel to pause. Use -1 to pause all channels.
 */
void Mix_Pause(int channel) {
}

/**
 * Sets a callback function to be invoked when a channel finishes playback.
 *
 * This function allows the application to register a callback that will be
 * called whenever a sound channel finishes playing. The callback function
 * receives the channel number as an argument, allowing the application to
 * perform specific actions or cleanup when a channel becomes available.
 *
 * @param channel_finished A pointer to the callback function that will be
 *                         called when a channel finishes playback. The callback
 *                         function should accept a single integer parameter
 *                         representing the channel number. If NULL is passed,
 *                         any previously set callback will be removed.
 */
void Mix_ChannelFinished(void (*channel_finished)(int channel)) {
}

// Music

Mix_Music *Mix_LoadMUS(const char *file) {
  return NULL;
}

/**
 * @brief Loads a music file from an SDL_RWops source.
 *
 * This function attempts to load a music file from the provided SDL_RWops source.
 * The supported formats depend on the SDL_mixer library's configuration and may
 * include formats such as WAV, MOD, MIDI, OGG, MP3, and FLAC. The function returns
 * a pointer to a Mix_Music object representing the loaded music, or NULL if the
 * loading fails.
 *
 * @param src A pointer to an SDL_RWops structure that provides the data source
 *            for the music file. The SDL_RWops must be opened and ready for reading.
 * @return A pointer to the loaded Mix_Music object on success, or NULL on failure.
 */
Mix_Music *Mix_LoadMUS_RW(SDL_RWops *src) {
  return NULL;
}

/**
 * Frees the memory allocated for a Mix_Music object.
 *
 * This function deallocates the resources associated with the given Mix_Music object.
 * After calling this function, the pointer to the Mix_Music object should no longer be used,
 * as it will be invalid. It is safe to call this function with a NULL pointer, in which case
 * the function does nothing.
 *
 * @param music A pointer to the Mix_Music object to be freed. If NULL, the function does nothing.
 */
void Mix_FreeMusic(Mix_Music *music) {
}

/**
 * Plays the specified music with the given number of loops.
 *
 * This function starts playing the provided `Mix_Music` object. The music will
 * loop continuously for the specified number of `loops`. If `loops` is set to -1,
 * the music will loop indefinitely until stopped. 
 *
 * @param music Pointer to the `Mix_Music` object to be played.
 * @param loops Number of times the music should loop. Use -1 for infinite looping.
 * @return 0 on success, or a non-zero value if an error occurs.
 */
int Mix_PlayMusic(Mix_Music *music, int loops) {
  return 0;
}

/**
 * Sets the playback position of the currently playing music to the specified time.
 *
 * This function allows you to seek to a specific point in the music track. The position
 * is specified in seconds from the start of the music. If the music is not playing or
 * the position is invalid (e.g., negative or beyond the end of the track), the function
 * will return an error.
 *
 * @param position The desired playback position in seconds.
 * @return 0 on success, or a negative value on error.
 */
int Mix_SetMusicPosition(double position) {
  return 0;
}

/**
 * Sets the volume for the currently playing music.
 *
 * This function adjusts the volume of the music playback to the specified level.
 * The volume parameter should be a value between 0 and 128, where 0 is silence,
 * 128 is the maximum volume, and values outside this range are clamped.
 *
 * @param volume The desired volume level, ranging from 0 to 128.
 * @return The previous volume level before the change. If no music is playing,
 *         or if the volume cannot be set, this function returns 0.
 */
int Mix_VolumeMusic(int volume) {
  return 0;
}

/**
 * Sets the external command used to play music files.
 *
 * This function allows you to specify an external command that will be used
 * to play music files. The command should be a valid system command that can
 * be executed from the shell. The command string can include placeholders for
 * the music file path, which will be substituted at runtime.
 *
 * @param command The external command to use for playing music files. If NULL,
 *                the default command will be restored.
 *
 * @return 0 on success, or -1 if an error occurred (e.g., invalid command).
 */
int Mix_SetMusicCMD(const char *command) {
  return 0;
}

/**
 * Stops the currently playing music track and frees any associated resources.
 * This function halts the playback of the music, ensuring that no further audio
 * is produced. It is typically used to cleanly stop music playback before
 * switching to a different track or shutting down the audio system.
 *
 * @return int Returns 0 on success, indicating that the music was successfully halted.
 */
int Mix_HaltMusic() {
  return 0;
}

/**
 * @brief Sets a callback function to be invoked when the current music playback finishes.
 *
 * This method allows the user to specify a custom function that will be called
 * automatically when the currently playing music track ends. The callback function
 * should have no parameters and no return value.
 *
 * @param music_finished A pointer to the callback function to be executed when the music finishes.
 *                       If NULL, the current callback is removed.
 */
void Mix_HookMusicFinished(void (*music_finished)()) {
}

/**
 * Checks whether music is currently playing in the audio mixer.
 *
 * This function returns an integer indicating whether music is currently being played.
 * A return value of 0 means no music is playing, while a non-zero value indicates that
 * music is active.
 *
 * @return int 0 if no music is playing, non-zero if music is playing.
 */
int Mix_PlayingMusic() {
  return 0;
}
