/***************************************************************************************
* Copyright (c) 2014-2024 Zihao Yu, Nanjing University
*
* NEMU is licensed under Mulan PSL v2.
* You can use this software according to the terms and conditions of the Mulan PSL v2.
* You may obtain a copy of Mulan PSL v2 at:
*          http://license.coscl.org.cn/MulanPSL2
*
* THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND,
* EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT,
* MERCHANTABILITY OR FIT FOR A PARTICULAR PURPOSE.
*
* See the Mulan PSL v2 for more details.
***************************************************************************************/

#include <isa.h>
#include <memory/vaddr.h>

/**
 * @brief Raises an interrupt or exception by indexing the Interrupt Descriptor Table (IDT).
 *
 * This function is responsible for triggering an interrupt or exception by using the provided
 * interrupt number (`NO`) to index into the IDT. The IDT is a data structure used by the CPU
 * to determine the appropriate handler for a given interrupt or exception. The function also
 * takes a return address (`ret_addr`) which may be used by the interrupt handler to resume
 * execution after handling the interrupt.
 *
 * @param NO The interrupt number used to index the IDT.
 * @param ret_addr The return address where execution should continue after handling the interrupt.
 * @return word_t Returns 0 upon successful execution. The actual handling of the interrupt
 *         is performed by the appropriate interrupt handler as determined by the IDT.
 */
word_t isa_raise_intr(word_t NO, vaddr_t ret_addr) {
  /* TODO: Trigger an interrupt/exception with ``NO''.
   * That is, use ``NO'' to index the IDT.
   */

  return 0;
}

/**
 * @brief Handles the interrupt generated by a query operation.
 *
 * This method is invoked when an interrupt is triggered during a query operation.
 * It is responsible for managing the interrupt, ensuring that the query operation
 * is either completed successfully or appropriately terminated in case of an error.
 * The method may also perform necessary cleanup operations and log relevant information
 * for debugging purposes.
 */
void query_intr() {
}
