#include <am.h>
#include <klib.h>

#ifndef __ISA_NATIVE__

/**
 * @brief Handles dynamic shared object (DSO) initialization and finalization.
 *
 * This function is a special symbol used by the C++ runtime to manage the
 * initialization and destruction of global objects in dynamic shared objects
 * (DSOs). It is automatically called by the runtime when a DSO is loaded or
 * unloaded, ensuring that global constructors and destructors are executed
 * in the correct order. The function itself does not perform any operations
 * but serves as a placeholder for the runtime to hook into.
 *
 * @note This function is typically defined by the compiler and should not be
 *       modified or overridden unless specific custom behavior is required.
 */
void __dso_handle() {
}

/**
 * @brief Acquires a guard for a static local variable initialization.
 *
 * This function is part of the C++ runtime and is used to ensure that the
 * initialization of a static local variable is thread-safe and happens exactly
 * once. It is typically called by the compiler-generated code before the
 * initialization block of a static local variable.
 *
 * The function checks if the static variable has already been initialized.
 * If it has not been initialized, it acquires a guard to prevent other threads
 * from initializing the same variable concurrently. If the variable has already
 * been initialized, the function returns immediately.
 *
 * @note This function is usually paired with `__cxa_guard_release` to release
 * the guard after the initialization is complete.
 *
 * @return Returns 1 if the caller should proceed with the initialization,
 *         and 0 if the initialization has already been completed by another
 *         thread.
 */
void __cxa_guard_acquire() {
}

/**
 * @brief Releases the guard for a static local variable initialization.
 *
 * This function is part of the C++ runtime and is used to manage the 
 * initialization of static local variables. It is called after the 
 * initialization of the static local variable is complete, signaling 
 * that the guard can be released. This ensures that subsequent calls 
 * to the function will not attempt to reinitialize the static variable.
 *
 * The guard mechanism prevents multiple threads from simultaneously 
 * initializing the same static local variable, ensuring thread safety 
 * during the initialization phase.
 *
 * @note This function is typically generated by the compiler and should 
 * not be called directly by user code.
 */
void __cxa_guard_release() {
}

/**
 * @brief Registers a function to be called by exit() or when a shared library is unloaded.
 *
 * This function is intended to be used by the C++ runtime to register destructors for 
 * global and static objects. When the program exits or a shared library is unloaded, 
 * the registered function will be called to clean up resources. In this implementation, 
 * the function simply asserts and terminates the program, indicating that it is not 
 * properly implemented or should not be called.
 *
 * @note This implementation is a stub and will cause the program to terminate if called.
 */
void __cxa_atexit() {
  assert(0);
}

#endif
