#include <am.h>
#include <klib.h>
#include <klib-macros.h>

#if !defined(__ISA_NATIVE__) || defined(__NATIVE_USE_KLIB__)
static unsigned long int next = 1;

/**
 * Generates a pseudo-random integer using a linear congruential generator (LCG).
 * 
 * The method uses the formula `next = next * 1103515245 + 12345` to update the internal state
 * of the generator. The generated value is derived by dividing the updated state by 65536
 * and taking the result modulo 32768, ensuring the output is within the range [0, 32767].
 * 
 * The method assumes `RAND_MAX` is 32767, which is the maximum value that can be returned.
 * 
 * @return A pseudo-random integer between 0 and 32767 (inclusive).
 */
int rand(void) {
  // RAND_MAX assumed to be 32767
  next = next * 1103515245 + 12345;
  return (unsigned int)(next/65536) % 32768;
}

/**
 * Initializes the random number generator with a specified seed value.
 * 
 * This function sets the internal state of the random number generator
 * to a value based on the provided seed. The seed determines the sequence
 * of pseudo-random numbers that will be generated by subsequent calls to
 * the rand() function. Using the same seed will result in the same sequence
 * of random numbers, which can be useful for debugging or reproducibility.
 *
 * @param seed The seed value used to initialize the random number generator.
 */
void srand(unsigned int seed) {
  next = seed;
}

/**
 * Computes the absolute value of an integer.
 * 
 * The absolute value of a number is its distance from zero on the number line,
 * regardless of its direction. This function returns the non-negative value
 * of the input integer. If the input is negative, it returns the negation of
 * the input; otherwise, it returns the input itself.
 * 
 * @param x The integer for which to compute the absolute value.
 * @return The absolute value of the input integer.
 */
int abs(int x) {
  return (x < 0 ? -x : x);
}

/**
 * Converts a string to an integer.
 * 
 * The function skips any leading whitespace characters and then processes
 * the subsequent characters as digits to form an integer. The conversion
 * stops when a non-digit character is encountered.
 * 
 * @param nptr A pointer to the null-terminated string to be converted.
 * @return The converted integer value. If no valid digits are found, 
 *         the function returns 0.
 */
int atoi(const char* nptr) {
  int x = 0;
  while (*nptr == ' ') { nptr ++; }
  while (*nptr >= '0' && *nptr <= '9') {
    x = x * 10 + *nptr - '0';
    nptr ++;
  }
  return x;
}

/**
 * Allocates a block of memory of the specified size.
 *
 * This function attempts to allocate a contiguous block of memory of the given size.
 * On native systems, `malloc()` is called during the initialization of the C runtime.
 * To avoid a deadlock scenario where `panic()` triggers `putchar()`, which in turn
 * calls `malloc()` and leads back to `panic()`, this function does not call `panic()`
 * directly. Instead, it returns `NULL` if the allocation is not implemented or fails.
 *
 * @param size The number of bytes to allocate.
 * @return A pointer to the allocated memory block, or `NULL` if the allocation is
 *         not implemented or fails.
 */
void *malloc(size_t size) {
  // On native, malloc() will be called during initializaion of C runtime.
  // Therefore do not call panic() here, else it will yield a dead recursion:
  //   panic() -> putchar() -> (glibc) -> malloc() -> panic()
#if !(defined(__ISA_NATIVE__) && defined(__NATIVE_USE_KLIB__))
  panic("Not implemented");
#endif
  return NULL;
}

/**
 * Frees the memory space pointed to by `ptr`, which must have been returned by a previous call to `malloc`, `calloc`, or `realloc`.
 * If `ptr` is NULL, no operation is performed. After calling `free`, the memory previously allocated is no longer accessible
 * and should not be used. The behavior is undefined if `ptr` does not point to a valid memory block allocated by one of the
 * aforementioned functions or if the memory has already been freed.
 *
 * @param ptr Pointer to the memory block to be freed. If `ptr` is NULL, the function does nothing.
 */
void free(void *ptr) {
}

#endif
